### PR TITLE
Adding Archive directory and cleaning up old ebuilds

### PR DESCRIPTION
**Pull request by Zorziel**
As mentioned in https://github.com/pbek/QOwnNotes/issues/1488 and  https://github.com/Zorziel/qownnotes-gentoo-overlay/issues/1 , the [ebuild directory](https://github.com/qownnotes/gentoo-overlay/tree/master/app-office/qownnotes) had a large amount of outdated ebuilds in it.  This request adds an Archive folder that's included in the .gitignore and moves the older ebuilds there.

### CODE REVIEW

**Comment by pbek** [comment]
Thank you 😁

**Comment by Zorziel** [comment]
Crap, I just realized that my mass mv with wildcards messed with some of the older versions names.  Doesn't matter for production use, but if anyone is going back and looking at older ebuilds, some 340 or so may have an incorrect file name.  

Not sure if this needs to be addressed for this push though.

**Comment by pbek** [comment]
> Not sure if this needs to be addressed for this push though.

You decide, I have no real means to test it anyway. 😅

**Comment by Zorziel** [comment]
Yes.  Sorry @pbek, I'd like to do it right this time.  Please give me a few minutes.

**Comment by pbek** [comment]
Is there a reason that more later releases like  app-office/qownnotes/qownnotes-21.12.8.ebuild are just deleted (and not archived)?

**Comment by Zorziel** [comment]
This happened because of how I initially "moved" (for example, using `mv *-21* Archive/`), which caused some files to be renamed in the sub-version part of the file name during the move.  

I removed all ebuilds from the Archive folder and copied fresh ones in with commit https://github.com/qownnotes/gentoo-overlay/pull/4/commits/592f3ad4b1c523367ebaca7b28fbd7194194a4ee just to be sure I didn't miss one.

**Comment by pbek** [comment]
> https://github.com/Zorziel/qownnotes-gentoo-overlay/commit/592f3ad4b1c523367ebaca7b28fbd7194194a4ee

I can't find anything about 21.12.8 in that commit 😅

**Comment by Zorziel** [comment]
Jeez, I'm sorry.  And here I thought I nailing it.  

https://github.com/qownnotes/gentoo-overlay/pull/4/commits/f5eb587c958b7fcefc61e9ea60a15eb05507a495 submitted.  Verified the 21.12 versions have been restored.

**Comment by pbek** [comment]
LGTM now 😁  thank you!

**Pull request merged**
